#!/usr/bin/env bash
# =====================================================================
# install-freecad.sh
#
# Why:  Install the FreeCAD built by build-freecad.sh and make it usable like
#       a normal Linux app: launch from the app menu, a `freecad` command, and
#       open .FCStd files by double-click. Kept separate from the build so a
#       rebuild/dev build never changes the installed copy until you run this.
# What: 1. checks the release build exists (build/release)
#       2. installs it into the pixi env (`pixi run install-release`, i.e.
#          cmake --install): this OVERWRITES the currently installed copy
#       3. per-user deploy under ~/.local (no sudo, nothing system-wide):
#          launchers ~/.local/bin/freecad and freecadcmd (run the pixi env's
#          FreeCAD so Qt/Python paths are right), app-menu entry, icons,
#          MIME types (.FCStd etc.), then refreshes the caches
#       Re-runnable. `--uninstall` removes only the deploy (launchers, menu
#       entry, icons, MIME); the installed copy in the pixi env is left alone.
#       The files point at the checkout, so don't move/delete this checkout.
#
# Log:     build/logs/install-freecad.log (in the git-ignored build/; local only)
# Run:     bash <path-to-this-script> [--uninstall]
# =====================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_NAME="$(basename "${BASH_SOURCE[0]}" .sh)"
LOG_DIR="$SCRIPT_DIR/../../build/logs"
LOG_FILE="$LOG_DIR/$SCRIPT_NAME.log"
mkdir -p "$LOG_DIR"

# Send all output (stdout + stderr) to both the terminal and the log.
exec > >(tee -a "$LOG_FILE") 2>&1

log()  { echo "[$(date '+%F %T')] $*"; }
step() { log "==> $*"; }

trap 'log "FAILED (exit $?) at line $LINENO: $BASH_COMMAND"' ERR
trap 'log "Finished with exit code $?"' EXIT

log "===== Start: $SCRIPT_NAME (user: $USER, host: $(hostname)) ====="

# ---------------------------------------------------------------------
FC_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
ENV_DIR="$FC_DIR/.pixi/envs/default"
PIXI="$HOME/.pixi/bin/pixi"
BIN_DIR="$HOME/.local/bin"
SHARE="$HOME/.local/share"
APP_ID="org.freecad.FreeCAD"
DESKTOP="$SHARE/applications/$APP_ID.desktop"
MIME_XML="$SHARE/mime/packages/$APP_ID.xml"

refresh_caches() {
    step "Refresh desktop, MIME and icon caches"
    update-desktop-database "$SHARE/applications" || true
    update-mime-database "$SHARE/mime" || true
    gtk-update-icon-cache -q -f -t "$SHARE/icons/hicolor" 2>/dev/null || true
}

if [ "${1:-}" = "--uninstall" ]; then
    step "Remove FreeCAD desktop deploy (installed copy in the pixi env is kept)"
    rm -fv "$BIN_DIR/freecad" "$BIN_DIR/freecadcmd" "$DESKTOP" "$MIME_XML"
    find "$SHARE/icons/hicolor" -name "$APP_ID.*" -print -delete 2>/dev/null || true
    refresh_caches
    log "===== Done (uninstalled): $SCRIPT_NAME ====="
    exit 0
fi

step "Check the release build exists"
[ -x "$PIXI" ] || { log "pixi not found at $PIXI (run build-freecad.sh first)"; exit 1; }
[ -x "$FC_DIR/build/release/bin/FreeCAD" ] || { log "no release build in $FC_DIR/build/release (run build-freecad.sh first)"; exit 1; }

step "Install the build into the pixi env (overwrites the installed copy)"
# cmake prints one line per file (~3600); show only a summary, keep failures visible.
INSTALL_OUT="$(mktemp)"
(cd "$FC_DIR" && "$PIXI" run --as-is install-release) > "$INSTALL_OUT" 2>&1 || { tail -30 "$INSTALL_OUT"; rm -f "$INSTALL_OUT"; exit 1; }
log "installed: $(grep -c 'Installing:' "$INSTALL_OUT") files updated, $(grep -c 'Up-to-date:' "$INSTALL_OUT") already up to date"
rm -f "$INSTALL_OUT"

step "Check the installed copy"
[ -x "$ENV_DIR/bin/FreeCAD" ] || { log "$ENV_DIR/bin/FreeCAD missing (run build-freecad.sh first)"; exit 1; }
[ -f "$ENV_DIR/share/applications/$APP_ID.desktop" ] || { log "desktop file missing in env"; exit 1; }

step "Write launchers in $BIN_DIR"
mkdir -p "$BIN_DIR"
for pair in "freecad:FreeCAD" "freecadcmd:FreeCADCmd"; do
    name="${pair%%:*}"; exe="${pair##*:}"
    cat > "$BIN_DIR/$name" <<LAUNCHER
#!/usr/bin/env bash
# Generated by $SCRIPT_NAME.sh: run FreeCAD from the pixi env in $FC_DIR
exec "$PIXI" run --as-is --manifest-path "$FC_DIR/pixi.toml" $exe "\$@"
LAUNCHER
    chmod +x "$BIN_DIR/$name"
    log "wrote $BIN_DIR/$name"
done

step "Install app-menu entry"
mkdir -p "$SHARE/applications"
sed "s|^Exec=FreeCAD |Exec=$BIN_DIR/freecad |" \
    "$ENV_DIR/share/applications/$APP_ID.desktop" > "$DESKTOP"
grep -E '^Exec=' "$DESKTOP"

step "Install icons"
(cd "$ENV_DIR/share/icons" && find hicolor -name "$APP_ID.*" -print0) |
while IFS= read -r -d '' f; do
    mkdir -p "$SHARE/icons/$(dirname "$f")"
    cp -v "$ENV_DIR/share/icons/$f" "$SHARE/icons/$f"
done

step "Install MIME types (.FCStd etc.)"
mkdir -p "$SHARE/mime/packages"
cp -v "$ENV_DIR/share/mime/packages/$APP_ID.xml" "$MIME_XML"

refresh_caches

step "Check $BIN_DIR is on PATH"
case ":$PATH:" in
    *":$BIN_DIR:"*) log "yes" ;;
    *) log "NOT on PATH in this shell. Log out/in (Mint adds ~/.local/bin if it exists) or run $BIN_DIR/freecad directly." ;;
esac

log "===== Done: $SCRIPT_NAME ====="
